### ISSUE TITLE
[ERROR][12-10-2023 21:13:35]: Validation Error: [ VUID-VkImageCreateInfo-pNext-01443 ]

### ISSUE THREAD

**Issue by Wit111** [damian-tomczak/tsengine#30]
API_DUMPS show that app asks 7 times for VKCreateImage but we only see 2 while debugging before error:
``
[ERROR][12-10-2023 21:13:35]: Validation Error: [ VUID-VkImageCreateInfo-pNext-01443 ] Object 0: handle = 0x206f4ab4080, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x18d987f6 | vkCreateImage: VkImageCreateInfo pNext chain includes VkExternalMemoryImageCreateInfo with handleTypes 16 but pCreateInfo->initialLayout is VK_IMAGE_LAYOUT_PREINITIALIZED. The Vulkan spec states: If the pNext chain includes a VkExternalMemoryImageCreateInfo or VkExternalMemoryImageCreateInfoNV structure whose handleTypes member is not 0, initialLayout must be VK_IMAGE_LAYOUT_UNDEFINED (https://vulkan.lunarg.com/doc/view/1.3.250.1/windows/1.3-extensions/vkspec.html#VUID-VkImageCreateInfo-pNext-01443)
``

**Comment by damian-tomczak** [comment]
HTC's xr runtime creates VkImages without caring about resetting not used fields.
